= Note legali
:allow-uri-read: 


<<<<<<< HEAD --- permalink: legal-notices.html barra laterale: parole chiave della barra laterale: riepilogo: ---



= Note legali

[role="lead"]
Le note legali forniscono accesso a dichiarazioni di copyright, marchi commerciali, brevetti e altro ancora.



== Copyright

link:https://www.netapp.com/company/legal/copyright/["https://www.netapp.com/company/legal/copyright/"^]



== Marchi

NETAPP, il logo NETAPP e i marchi elencati nella pagina Marchi NetApp sono marchi di NetApp, Inc. Altri nomi di aziende e prodotti possono essere marchi dei rispettivi proprietari.

link:https://www.netapp.com/company/legal/trademarks/["https://www.netapp.com/company/legal/trademarks/"^]



== Brevetti

Un elenco aggiornato dei brevetti di proprietà di NetApp è disponibile all'indirizzo:

link:https://www.netapp.com/pdf.html?item=/media/11887-patentspage.pdf["https://www.netapp.com/pdf.html?item=/media/11887-patentspage.pdf"^]



== Politica sulla riservatezza

link:https://www.netapp.com/company/legal/privacy-policy/["https://www.netapp.com/company/legal/privacy-policy/"^]



== Open source

I file di avviso forniscono informazioni sui diritti d'autore e sulle licenze di terze parti utilizzati nel software NetApp .

* https://docs.netapp.com/us-en/bluexp-setup-admin/media/notice.pdf["Avviso per la console NetApp"^]


[]
====
'''
permalink: legal-notices.html sidebar: sidebar keywords: # nessuna parola chiave summary: # nessun riepilogo --- = Note legali :icons: font :imagesdir: ./media/

[role="lead"]
Le note legali forniscono accesso a dichiarazioni di copyright, marchi commerciali, brevetti e altro ancora.

== Diritto d'autore

link:https://www.netapp.com/company/legal/copyright/["https://www.netapp.com/company/legal/copyright/"^]

== Marchi

NETAPP, il logo NETAPP e i marchi elencati nella pagina Marchi NetApp sono marchi di NetApp, Inc. Altri nomi di aziende e prodotti possono essere marchi dei rispettivi proprietari.

link:https://www.netapp.com/company/legal/trademarks/["https://www.netapp.com/company/legal/trademarks/"^]

== Brevetti

Un elenco aggiornato dei brevetti di proprietà di NetApp è disponibile all'indirizzo:

link:https://www.netapp.com/pdf.html?item=/media/11887-patentspage.pdf["https://www.netapp.com/pdf.html?item=/media/11887-patentspage.pdf"^]

== Informativa sulla privacy

link:https://www.netapp.com/company/legal/privacy-policy/["https://www.netapp.com/company/legal/privacy-policy/"^]

== Open source

I file di avviso forniscono informazioni sui diritti d'autore e sulle licenze di terze parti utilizzati nel software NetApp .

>>>>>>> db096cfa4bc2bcbc1a7a0fefc9249c9cbef4831b

====