---
settings:
  name: NetApp Ransomware Resilience
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  release_notes_autogen:
    release_notes_repo: console-relnotes
  rss_page: whats-new.html
  langs: it-it,us-en,de-de,es-es,fr-fr,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentazione NetApp Ransomware Resilience
    url: "/index.html"
  - title: Note di rilascio
    entries:
    - title: Novità in Ransomware Resilience
      url: "/whats-new.html"
    - title: Limitazioni note
      url: "/rp-reference-limitations.html"
  - title: Iniziare
    entries:
    - title: Scopri di più sulla resilienza al ransomware
      url: "/concept-ransomware-resilience.html"
    - title: Prerequisiti
      url: "/rp-start-prerequisites.html"
    - title: Avvio rapido
      url: "/rp-start-quick-start.html"
    - title: Imposta la resilienza al ransomware
      url: "/rp-start-setup.html"
    - title: Impostare la licenza
      url: "/rp-start-licenses.html"
    - title: Scopri i carichi di lavoro
      url: "/rp-start-discover.html"
  - title: Utilizzare la resilienza del ransomware
    entries:
    - title: Access Ransomware Resilience
      url: "/rp-start-login.html"
    - title: Visualizza lo stato di integrità del carico di lavoro
      url: "/rp-use-dashboard.html"
    - title: Proteggi e rileva
      entries:
      - title: Verifica protezione
        url: "/task-review-protection.html"
      - title: Configurare le destinazioni di backup
        url: "/task-backup-destination.html"
      - title: Proteggere i carichi di lavoro
        url: "/rp-use-protect.html"
      - title: Configura il rilevamento dell'attività dell'utente
        entries:
        - title: Scopri il rilevamento delle attività degli utenti
          url: "/concept-user-behavior.html"
        - title: Requisiti di rilevamento delle attività degli utenti
          url: "/reference-user-activity-requirements.html"
        - title: Configura agenti e collettori
          url: "/suspicious-user-activity.html"
      - title: Gestisci i gruppi di protezione
        url: "/task-protection-group.html"
      - title: Scansione per dati personali identificabili
        url: "/task-classify.html"
    - title: Rispondere e recuperare
      entries:
      - title: Rispondere a un avviso rilevato
        url: "/rp-use-alert.html"
      - title: Esaminare lo stato di recupero
        url: "/rp-use-recover.html"
      - title: Ripristina con un ripristino personalizzato
        url: "/rp-use-recover.html"
      - title: Eseguire un ripristino pulito
        entries:
        - title: Creare un ambiente di recovery isolato
          url: "/task-clean-restore.html"
        - title: Ripristina con un ripristino pulito
          url: "/task-clean-restore-recover.html"
    - title: Eseguire un'esercitazione di preparazione
      url: "/rp-start-simulate.html"
    - title: Configura SIEM
      url: "/task-siem.html"
    - title: Integra SOAR playbook
      url: "/reference-soar.html"
    - title: Scarica i report
      url: "/rp-use-reports.html"
  - section: support
  - title: Domande frequenti
    url: "/rp-start-faq.html"
  - title: Note legali
    url: "/legal-notices.html"
product-family:
  name: NetApp Data Services
  repo: data-services-family
