---
sidebar: sidebar 
permalink: rp-reference-limitations.html 
keywords: ransomware protection, protect against ransomware attacks, anti-ransomware, role-based access control, rbac, role, permission, access rights, organization,project,account 
summary: Le limitazioni note identificano piattaforme, dispositivi o funzioni non supportati da questa versione del prodotto. 
---
= Limitazioni note in NetApp Ransomware Resilience
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Le limitazioni note identificano piattaforme, dispositivi o funzioni che non sono supportati da questa versione del prodotto o che non interagiscono correttamente con esso. Esamina attentamente queste limitazioni.



[[readiness-drill-reset-option-issue]]
== Problema relativo all'opzione di ripristino dell'esercitazione di preparazione

Se si seleziona un volume ONTAP 9.11.1 per l'esercitazione di preparazione all'attacco ransomware, Ransomware Resilience invia un avviso.  Se si ripristinano i dati utilizzando l'opzione "clone-to-volume" e si reimposta il drill, l'operazione di reimpostazione fallisce.



[[amazon-fsx-for-netapp-ontap-limitations]]
== Limitazioni Amazon FSx for NetApp ONTAP

Le seguenti limitazioni si applicano ad Amazon FSx per ONTAP:

* Le policy di backup non sono supportate per Amazon FSx per ONTAP. In questo ambiente, dovresti eseguire le operazioni di backup utilizzando i backup di Amazon FSx. Puoi ripristinare questi workload utilizzando Ransomware Resilience.
* Le operazioni di ripristino vengono eseguite solo dagli snapshot.




[[azure-netapp-files-limitations]]
== Limitazioni di Azure NetApp Files

Le seguenti limitazioni si applicano ad Azure NetApp Files:

* Le strategie di protezione ransomware con criteri di backup non sono supportate per Azure NetApp Files. In alternativa, è possibile utilizzare il backup di Azure NetApp Files.
* Le strategie di protezione ransomware con replica non sono supportate per Azure NetApp Files.
* Azure NetApp Files non supporta FPolicy né il rilevamento del comportamento degli utenti. Azure NetApp Files non supporta nemmeno l'analisi forense dell'entropia.
* Quando si seleziona una strategia di protezione, assicurarsi che la pianificazione degli snapshot sia compatibile con Azure NetApp Files. La pianificazione degli snapshot più frequente disponibile in Azure NetApp Files è oraria.
* Si sconsiglia di utilizzare link:reference-soar.html["Playbook SOAR"] con Azure NetApp Files poiché le API di Azure NetApp Files bloccano le azioni automatizzate.
* Alcuni dati relativi agli eventi non sono inclusi in link:task-siem.html["Rapporti SIEM"] per le configurazioni di Azure NetApp Files.




[[google-cloud-netapp-volumes-limitations]]
== Limitazioni di Google Cloud NetApp Volumes

Le seguenti limitazioni si applicano a Google Cloud NetApp Volumes:

* Al momento, è possibile applicare solo strategie di protezione basate sulla crittografia e su FPolicy ai carichi di lavoro di Google Cloud NetApp Volumes. Non è possibile applicare strategie di protezione basate sul comportamento degli utenti.
* Le strategie di protezione con replica non sono attualmente supportate per Google Cloud NetApp Volumes.




[[san-storage-limitations]]
== Limitazioni di archiviazione SAN

Alle workload SAN (storage a blocchi) si applicano le seguenti limitazioni:

* Quando Ransomware Resilience genera avvisi per i carichi di lavoro SAN, tali avvisi si basano solo su un'entropia elevata.
* I carichi di lavoro SAN possono essere ripristinati solo utilizzando un link:task-custom-restore.html["ripristino personalizzato"]. Il ripristino pulito non è attualmente disponibile per i carichi di lavoro SAN.




[[multi-admin-verification]]
== Verifica multi-amministratore

La verifica multi-amministratore non è supportata in Ransomware Resilience o nella NetApp Console. Se hai configurato link:https://docs.netapp.com/us-en/ontap/multi-admin-verify/["Verifica multi-amministratore in ONTAP"^], non potrai abilitare la protezione, eseguire un'esercitazione di preparazione o effettuare operazioni di ripristino. Dovresti disabilitare la verifica multi-amministratore prima di provare una di queste operazioni.
