---
sidebar: sidebar 
permalink: rp-start-prerequisites.html 
keywords: bluexp ransomware protection, ransomware protection prerequisites, resilience 
summary: 'Inizia a usare NetApp Ransomware Resilience verificando il supporto per il tuo ambiente, l"accesso alla rete, l"accesso e il browser web.' 
---
= Prerequisiti per la resilienza al ransomware NetApp
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/get-started/


[role="lead"]
Inizia a usare NetApp Ransomware Resilience verificando la preparazione del tuo ambiente operativo, delle credenziali di accesso, dell'accesso alla rete e del browser web.

Per utilizzare Ransomware Resilience, è necessario soddisfare i seguenti prerequisiti.



== Nella console NetApp

* Un account utente della console NetApp con privilegi di amministratore dell'organizzazione per l'individuazione delle risorse.
* Un'organizzazione Console con almeno un agente Console attivo che si connette ai cluster ONTAP locali o a Cloud Volumes ONTAP in AWS o in Azure.
* L'agente della console deve avere `cloudmanager-ransomware-protection` contenitore in stato attivo.
* Almeno un sistema Console con un cluster ONTAP locale NetApp o Cloud Volumes ONTAP in AWS o Azure.  Ransomware Resilience supporta sia i protocolli NAS (NFS e SMB) sia SAN (iSCSI, FC e NVMe).
+
** Sono supportati i cluster ONTAP o Cloud Volumes ONTAP con versione ONTAP OS 9.11.1 o successiva.
+

NOTE: I carichi di lavoro SAN sono supportati solo in ONTAP 9.17.1 e versioni successive.

** Se i cluster ONTAP locali o Cloud Volumes ONTAP in AWS o nel cloud di Azure non sono già integrati nella Console, è necessario un agente della Console.
+
Fare riferimento a https://docs.netapp.com/us-en/console-setup-admin/concept-connectors.html["Scopri come configurare un agente Console"] E https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-checklist-cm.html["requisiti standard della console"^] .

+

NOTE: Se sono presenti più agenti Console in un'unica organizzazione Console, Ransomware Resilience analizzerà le risorse ONTAP su tutti gli agenti Console, a parte quello attualmente selezionato nell'interfaccia utente della Console.







== In ONTAP 9.11.1 e versioni successive

* Una licenza ONTAP One è abilitata sull'istanza ONTAP locale.
* Una licenza per NetApp Autonomous Ransomware Protection, utilizzata da Ransomware Resilience, abilitata sull'istanza ONTAP locale, a seconda della versione di ONTAP in uso. Fare riferimento a https://docs.netapp.com/us-en/ontap/anti-ransomware/index.html["Panoramica sulla protezione autonoma dal ransomware"^] .
+

NOTE: La versione generale di Ransomware Resilience, a differenza della versione Preview, include una licenza per la tecnologia NetApp Autonomous Ransomware Protection. Fare riferimento a https://docs.netapp.com/us-en/ontap/anti-ransomware/index.html["Panoramica sulla protezione autonoma dal ransomware"^] per i dettagli.

+
Per maggiori dettagli sulla licenza, fare riferimento alink:concept-ransomware-resilience.html["Scopri di più sulla resilienza al ransomware"] .

* Per applicare le configurazioni di protezione (ad esempio, l'abilitazione della protezione autonoma contro i ransomware e altre), Ransomware Resilience necessita delle autorizzazioni di amministratore sul cluster ONTAP .  Il cluster ONTAP avrebbe dovuto essere integrato utilizzando solo le credenziali utente amministratore del cluster ONTAP .
* Se il cluster ONTAP è già stato integrato nella Console utilizzando credenziali utente non amministratore, le autorizzazioni dell'utente non amministratore devono essere aggiornate con le autorizzazioni necessarie effettuando l'accesso al cluster ONTAP , come descritto in questa pagina.




== Per i backup dei dati

* Un account in NetApp StorageGRID, AWS S3, Azure Blob o Google Cloud Platform per le destinazioni di backup e le autorizzazioni di accesso impostate.
+
Fare riferimento al https://docs.netapp.com/us-en/console-setup-admin/reference-permissions.html["Elenco delle autorizzazioni AWS, Azure o S3"^] per i dettagli.

* Non è necessario abilitare NetApp Backup and Recovery sul sistema.
+
Ransomware Resilience aiuta a configurare una destinazione di backup tramite l'opzione Impostazioni. Vedere link:rp-use-settings.html["Configurare le impostazioni"] .





== Aggiornare le autorizzazioni degli utenti non amministratori in un sistema ONTAP

Se è necessario aggiornare le autorizzazioni degli utenti non amministratori per un sistema specifico, completare questi passaggi.

. Accedi alla Console e cerca il sistema che necessita di aggiornare le autorizzazioni utente ONTAP .
. Seleziona il sistema per visualizzarne i dettagli.
. Selezionare *Visualizza informazioni aggiuntive* per visualizzare il nome utente.
. Accedere alla CLI del cluster ONTAP utilizzando l'utente amministratore.
. Visualizza i ruoli esistenti per quell'utente. Inserisci:
+
[listing]
----
security login show -user-or-group-name <username>
----
. Cambia il ruolo dell'utente. Inserisci:
+
[listing]
----
security login modify -user-or-group-name <username> -application console|http|ontapi|ssh|telnet -authentication-method password -role admin
----
. Per utilizzarlo, tornare all'interfaccia utente di Ransomware Resilience.

