---
sidebar: sidebar 
permalink: rp-start-setup.html 
keywords: bluexp, ransomware protection, aws, azure 
summary: Per utilizzare Ransomware Resilience, è necessario eseguire alcuni passaggi per configurarlo. 
---
= Imposta NetApp Ransomware Resilience
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Configura NetApp Ransomware Resilience preparando una destinazione di backup, verificando i prerequisiti e configurando la NetApp Console e l'agente della Console.



[[prepare-the-backup-destination]]
== Preparare la destinazione del backup

Preparare una delle seguenti destinazioni di backup:

* NetApp StorageGRID
* Servizi Web Amazon
* Piattaforma Google Cloud
* Microsoft Azure


Dopo aver configurato le opzioni nella destinazione di backup stessa, sarà possibile configurarla successivamente come destinazione di backup in Ransomware Resilience. Per dettagli su come configurare la destinazione di backup in Ransomware Resilience, consultare link:task-backup-destination.html["Configurare le destinazioni di backup"].



[[prepare-storagegrid-to-become-a-backup-destination]]
=== Preparare StorageGRID per diventare una destinazione di backup

Se si desidera utilizzare StorageGRID come destinazione di backup, fare riferimento a https://docs.netapp.com/us-en/storagegrid-117/index.html["Documentazione StorageGRID"^] per i dettagli su StorageGRID.



[[prepare-aws-to-become-a-backup-destination]]
=== Preparare AWS a diventare una destinazione di backup

* Crea un account su AWS.
* Configurare https://docs.netapp.com/us-en/console-setup-admin/reference-permissions.html["Autorizzazioni AWS"^] in AWS.


Per i dettagli sulla gestione dell'archiviazione AWS nella Console, fare riferimento a https://docs.netapp.com/us-en/console-setup-admin/task-viewing-amazon-s3.html["Gestisci i tuoi bucket Amazon S3"^] .



[[prepare-azure-to-become-a-backup-destination]]
=== Preparare Azure per diventare una destinazione di backup

* Configura un account in Azure.
* Configurare https://docs.netapp.com/us-en/console-setup-admin/reference-permissions.html["Autorizzazioni di Azure"^] in Azzurro.


Per informazioni dettagliate sulla gestione dell'archiviazione di Azure nella console, fare riferimento a https://docs.netapp.com/us-en/storage-management-blob-storage/task-view-azure-blob-storage.html["Gestisci i tuoi account di archiviazione di Azure"^] .



[[set-up-the-netapp-console]]
== Configurare la NetApp Console

Il passo successivo consiste nell'impostare la NetApp Console e NetApp Ransomware Resilience.

Revisione https://docs.netapp.com/us-en/console-setup-admin/task-quick-start-standard-mode.html["Requisiti della console per la modalità standard"^] .



[[create-a-console-agent]]
=== Creare un agente Console

Contatta il tuo NetApp sales representative per provare o utilizzare questo servizio. Poi l'agente della Console include le funzionalità necessarie per Ransomware Resilience.

Per creare un agente Console per Ransomware Resilience, contatta l'amministratore dell'organizzazione Console che ha il permesso di creare agenti Console e fai riferimento a  https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-connectors.html["come creare un agente Console"^].


NOTE: Se hai più agenti Console, Ransomware Resilience analizza i dati di tutti gli agenti Console, non solo di quello attualmente visualizzato nella Console. Il servizio analizza i dati di tutti i progetti e gli agenti Console associati all'organizzazione.
