---
sidebar: sidebar 
permalink: rp-start-faq.html 
keywords: ransomware protection faq, ransomware protection frequently asked questions 
summary: Trova la risposta a una domanda frequente su NetApp Ransomware Resilience. 
---
= FAQ per NetApp Ransomware Resilience
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Questa sezione FAQ può aiutarti se stai cercando una risposta rapida a una domanda su NetApp Ransomware Resilience.



== Distribuzione

.Hai bisogno di una licenza per utilizzare Ransomware Resilience?
È possibile utilizzare i seguenti tipi di licenza:

* Registrati per una prova gratuita di 30 giorni.
* Acquista un abbonamento pay-as-you-go (PAYGO) a NetApp Intelligent Services e Ransomware Resilience con Amazon Web Services (AWS) Marketplace, Google Cloud Marketplace e Microsoft Azure Marketplace.
* Bring your own license (BYOL), ovvero un file di licenza NetApp (NLF) che puoi ottenere dal tuo rappresentante di vendita NetApp . Puoi utilizzare il numero di serie della licenza per attivare BYOL nella sezione Licenses and subscriptions della Console.


.Come si abilita la Ransomware Resilience?
È possibile accedere a Ransomware Resilience dalla NetApp Console. Assicurati di aver link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-reference-roles.html["ruoli di accesso"] E link:rp-start-prerequisites.html["prerequisiti"]. Se hai configurato correttamente un agente Console, puoi quindi link:rp-start-discover.html["scoprire i carichi di lavoro"].

Per maggiori informazioni, vederelink:rp-start-login.html["Access Ransomware Resilience"] Elink:rp-start-quick-start.html["Guida rapida alla resilienza del ransomware"] .

.Ransomware Resilience è disponibile nelle modalità standard, limitata e privata?
Al momento, Ransomware Resilience è disponibile solo in modalità standard.

Per una spiegazione su queste modalità in tutti i servizi dati NetApp , fare riferimento a https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["Modalità di distribuzione NetApp Console"^] .

.Come funziona la fatturazione per Ransomware Resilience?
Puoi provare Ransomware Resilience con una prova gratuita di 30 giorni. NetApp non addebita alcun costo per l'utilizzo della versione di prova di Ransomware Resilience.

Se disponi sia di Backup and Recovery che di Ransomware Resilience, tutti i dati comuni protetti da entrambi i prodotti verranno fatturati solo da Ransomware Resilience.

Quando un carico di lavoro viene classificato come protetto, viene conteggiato ai fini della capacità acquistata o dell'abbonamento PAYGO. Ransomware Resilience classifica un carico di lavoro come protetto quando è abilitata una policy di rilevamento con almeno una policy di backup o snapshot. I carichi di lavoro rilevati con una policy di rilevamento ma _senza_ alcuna policy di backup o snapshot vengono classificati come a rischio. I carichi di lavoro a rischio non vengono conteggiati ai fini della capacità acquistata.

I carichi di lavoro protetti vengono conteggiati nella capacità acquistata o nell'abbonamento al termine del periodo di prova gratuito. Ransomware Resilience viene addebitato in base ai GB per i dati associati ai carichi di lavoro protetti (come riportato da ONTAP) prima delle efficienze.

Nel calcolo delle dimensioni, i costi di licenza si basano sulla capacità logica del file system attivo (ovvero, lo spazio occupato dagli snapshot non è incluso).



== Accesso

.Qual è l'URL di Ransomware Resilience?
In un browser, inserisci https://console.netapp.com/["https://console.netapp.com/ransomware-resilience"^] per accedere alla Console.

.Come vengono gestiti i permessi di accesso?
https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Scopri di più sui ruoli di accesso alla console per tutti i servizi"^]. Ransomware Resilience ha anche link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-ransomware-roles.html["ruoli di accesso dedicati"^].

.Quale risoluzione del dispositivo è migliore?
La risoluzione del dispositivo consigliata per Ransomware Resilience è 1920x1080 o superiore.

.Quale browser dovrei usare?
È possibile accedere alla NetApp Console con qualsiasi browser Web moderno.



== Interoperabilità

.Ransomware Resilience è a conoscenza delle impostazioni di protezione in ONTAP?
Sì, Ransomware Resilience rileva le pianificazioni degli snapshot impostate in ONTAP.

.In che modo Ransomware Resilience interagisce con NetApp Backup and Recovery?
Ransomware Resilience works with Backup and Recovery per individuare e impostare policy di snapshot e backup per i carichi di lavoro di condivisione file. Ransomware Resilience works with Backup and Recovery anche per eseguire un ripristino coerente di file e carichi di lavoro.

Per quanto riguarda le licenze e la fatturazione, Ransomware Resilience può integrarsi con Backup and Recovery anche se non si dispone di una licenza separata per Backup and Recovery. Se disponi sia di Backup and Recovery che di Ransomware Resilience, tutti i dati comuni protetti da entrambi i prodotti verranno fatturati solo da Ransomware Resilience.



== Carichi di lavoro

.Cos'è un carico di lavoro nel contesto della resilienza al ransomware?
Un carico di lavoro è una macchina virtuale o una condivisione di file.

.In che modo Ransomware Resilience assegna la priorità ai dati del carico di lavoro?
La priorità del carico di lavoro (critica, standard, importante) è determinata dalle frequenze degli snapshot già applicate a ciascun volume associato al carico di lavoro e dai backup pianificati.

link:rp-use-protect.html["Scopri la priorità o l'importanza del carico di lavoro"] .

.Quali carichi di lavoro supporta Ransomware Resilience?
Ransomware Resilience è in grado di identificare i seguenti carichi di lavoro: Oracle, condivisioni di file, storage a blocchi, VM e datastore di VM.

.Come si associano i dati a un carico di lavoro?
Ransomware Resilience rileva i volumi e le estensioni dei file e li associa al carico di lavoro appropriato.

.Che cosa è un carico di lavoro protetto?
In Ransomware Resilience, un carico di lavoro mostra uno stato di *protetto* quando ha una policy di _rilevamento_ primaria abilitata, ovvero link:concept-ransomware-resilience.html["Protezione autonoma dal ransomware (ARP)"] è abilitato su tutti i volumi correlati al carico di lavoro.

.Che cosa si intende per carico di lavoro "a rischio"?
Se un carico di lavoro non ha un criterio di rilevamento primario abilitato, viene etichettato come "a rischio" anche se ha un criterio di backup e snapshot abilitato. Per la protezione dal ransomware, dovresti abilitare un link:rp-use-protect.html#add-a-ransomware-protection-strategy["politica di rilevamento"].

.Ho aggiunto un nuovo volume, ma non è ancora uscito. Cosa dovrei fare?
Se hai aggiunto un nuovo volume al tuo ambiente, avvia nuovamente l'individuazione del carico di lavoro. Dopo che il volume è stato scoperto, link:rp-use-protect.html#add-a-ransomware-protection-strategy["applicare policy di protezione per proteggere il nuovo volume"].



== Politiche di protezione

.Le policy ransomware Ransomware Resilience coesistono con altri tipi di policy relative ai carichi di lavoro?
Al momento, Backup e ripristino (Cloud Backup) supporta un criterio di backup per volume. Se si configura la protezione del backup con Backup e ripristino, questa condivide i criteri di backup con Ransomware Resilience.

Le copie snapshot non hanno limiti e possono essere aggiunte separatamente da ciascun servizio.

.Quali politiche sono richieste in una strategia di protezione dal ransomware?
UN link:rp-use-protect.html#add-a-ransomware-protection-strategy["strategia di protezione dal ransomware"] richiede:

* una politica di rilevamento del ransomware e
* una politica di snapshot


Nella strategia Ransomware Resilience non è richiesta una policy di backup.

.Ransomware Resilience è a conoscenza delle impostazioni di protezione in ONTAP?
Sì, Ransomware Resilience rileva le pianificazioni degli snapshot impostate in ONTAP. Rileva inoltre se ARP e FPolicy sono abilitati su tutti i volumi in un carico di lavoro rilevato. Le informazioni visualizzate nella dashboard di Ransomware Resilience sono aggregate da altre NetApp soluzioni e prodotti.

.Ransomware Resilience è a conoscenza delle policy già definite in NetApp Backup and Recovery?
Sì, se hai carichi di lavoro gestiti in Backup and Recovery, le policy gestite da tali prodotti vengono importate in Ransomware Resilience.

.È possibile modificare i criteri trasferiti da NetApp Backup and Recovery?
No, non è possibile modificare le policy gestite da Backup and Recovery da Ransomware Resilience. Gestisci eventuali modifiche a tali policy in Backup and Recovery.

.Se esistono policy di ONTAP (come ARP, FPolicy e snapshot), queste vengono modificate in Ransomware Resilience?
No. Ransomware Resilience non modifica alcuna policy di rilevamento esistente (impostazioni ARP, FPolicy) da ONTAP.

.Cosa succede se aggiungi nuove policy in Backup and Recovery dopo aver effettuato la registrazione a Ransomware Resilience?
Ransomware Resilience riconosce le policy appena create e le modifiche alle policy in NetApp Backup and Recovery.

.È possibile modificare le politiche di ONTAP?
Sì, è possibile modificare le policy da ONTAP in Ransomware Resilience.  È anche possibile creare nuove policy in Ransomware Resilience e applicarle ai carichi di lavoro.  Questa azione sostituisce le policy ONTAP esistenti con le policy create in Ransomware Resilience.

.È possibile disattivare le policy in ONTAP?
È possibile disabilitare ARP nei criteri di rilevamento tramite l'interfaccia utente di System Manager, le API o la CLI in ONTAP.

È possibile disattivare i criteri FPolicy e di backup applicando un criterio diverso che non li includa.
