---
sidebar: sidebar 
permalink: rp-start-prerequisites.html 
keywords: bluexp ransomware protection, ransomware protection prerequisites, resilience 
summary: 'Inizia a usare NetApp Ransomware Resilience verificando il supporto per il tuo ambiente, l"accesso alla rete, l"accesso e il browser web.' 
---
= Prerequisiti per la NetApp Ransomware Resilience
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/get-started/


[role="lead"]
Inizia a usare NetApp Ransomware Resilience verificando la preparazione del tuo ambiente operativo, dell'accesso alla rete e del browser web.

Per utilizzare Ransomware Resilience, assicurati di soddisfare i prerequisiti.



== Sistemi supportati

Assicurati di utilizzare un sistema supportato:

|===
| Ambiente | Protocollo | Versioni supportate 


| Amazon FSx for NetApp ONTAP* | NFS, CIFS e SAN | N / A 


.2+| Cloud Volumes ONTAP per AWS | CIFS e NFS | 9.11.1 e versioni successive 


| SAN (FC, iSCSI e NVMe) | 9.17.1 e versioni successive 


.2+| Cloud Volumes ONTAP per Google Cloud Platform | CIFS e NFS | 9.11.1 e versioni successive 


| SAN (FC, iSCSI e NVMe) | 9.17.1 e versioni successive 


.2+| Cloud Volumes ONTAP per Microsoft Azure | CIFS e NFS | 9.12.1 e versioni successive 


| SAN (FC, iSCSI e NVMe) | 9.17.1 e versioni successive 


.2+| ONTAP (in sede) | CIFS e NFS | 9.11.1 e versioni successive 


| SAN (FC, iSCSI e NVMe) | 9.17.1 e versioni successive 
|===
{asterisco} Amazon FSx for NetApp ONTAP utilizza Autonomous Ransomware Protection (ARP) e non ARP/AI.  Per maggiori informazioni sulla differenza, vederelink:https://docs.netapp.com/us-en/ontap/anti-ransomware/#arp-ai["ARP/IA"^] .



== Requisiti NetApp Console

La configurazione NetApp Console richiede:

* Un account utente NetApp Console con privilegi di amministratore dell'organizzazione per l'individuazione delle risorse.
* Un'organizzazione e un sistema di console con almeno un agente di console attivo che si connette a unlink:concept-ransomware-resilience.html#supported-backup-targets-systems-and-workload-data-sources["sistema supportato"] .
+
** Se i cluster ONTAP locali o Cloud Volumes ONTAP in AWS o nel cloud di Azure non sono configurati nella Console, vederelink:https://docs.netapp.com/us-en/console-setup-admin/concept-agents.html["Scopri come configurare un agente Console"^] Elink:https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-checklist-cm.html["requisiti standard della console"^] .
+

NOTE: Se sono presenti più agenti Console in un'unica organizzazione Console, Ransomware Resilience analizzerà le risorse ONTAP su tutti gli agenti Console, a parte quello attualmente selezionato nell'interfaccia utente della Console.



* L'agente della console deve avere `cloudmanager-ransomware-protection` contenitore in stato attivo.
* Almeno un sistema Console con un cluster ONTAP locale NetApp o Cloud Volumes ONTAP in AWS o Azure.  Ransomware Resilience supporta sia i protocolli NAS (NFS e SMB) sia SAN (iSCSI, FC e NVMe).
+
** Ransomware Resilience è supportato con i cluster ONTAP o Cloud Volumes ONTAP con ONTAP versione 9.11.1 o successiva.
+

NOTE: Per utilizzare Ransomware Resilience sui carichi di lavoro SAN, è necessario eseguire ONTAP 9.17.1 o versione successiva.







== Requisiti ONTAP

* È necessario eseguire ONTAP 9.11.1 o versione successiva con una licenza ONTAP One abilitata sull'istanza ONTAP locale.  Per ulteriori informazioni sul supporto ONTAP , vederelink:https://docs.netapp.com/us-en/ontap/anti-ransomware/index.html["Panoramica sulla protezione autonoma dal ransomware"^] .
* Per applicare le configurazioni di protezione (ad esempio, abilitando la protezione autonoma contro i ransomware), Ransomware Resilience necessita delle autorizzazioni di amministratore sul cluster ONTAP . Il cluster ONTAP avrebbe dovuto essere integrato utilizzando solo le credenziali utente amministratore del cluster ONTAP .



NOTE: Se hai connesso un cluster ONTAP alla Console con credenziali non amministrative, [devi aggiornare le credenziali nel cluster ONTAP ](#update-non-admin-user-permissions-in-an-ontap-system).



== Backup dei dati

* Un account in NetApp StorageGRID, AWS S3, Azure Blob o Google Cloud Platform per le destinazioni di backup con autorizzazioni di accesso appropriate configurate.
+
Fare riferimento al https://docs.netapp.com/us-en/console-setup-admin/reference-permissions.html["Elenco delle autorizzazioni AWS, Azure o S3"^] per i dettagli.

* Non è necessario abilitare NetApp Backup and Recovery sul sistema.
+
Ransomware Resilience aiuta a configurare una destinazione di backup tramite l'opzione Impostazioni. Vedere link:rp-use-settings.html["Configurare le impostazioni"] .





== Comportamento sospetto dell'utente

Affinché Ransomware Resilience fornisca avvisi sui comportamenti sospetti degli utenti, è necessario configurare un agente di attività utente. Per maggiori informazioni, vedere link:suspicious-user-activity.html["Configurare il rilevamento delle attività sospette degli utenti in NetApp Ransomware Resilience"].



== Aggiornare le autorizzazioni degli utenti non amministratori in un sistema ONTAP

Se è necessario aggiornare le autorizzazioni degli utenti non amministratori per un sistema specifico, completare questi passaggi.

. Accedi alla Console e cerca il sistema che necessita di aggiornare le autorizzazioni utente ONTAP .
. Seleziona il sistema per visualizzarne i dettagli.
. Selezionare *Visualizza informazioni aggiuntive* per visualizzare il nome utente.
. Accedere alla CLI del cluster ONTAP come utente amministratore.
. Visualizza i ruoli esistenti per quell'utente. Inserisci:
+
[listing]
----
security login show -user-or-group-name <username>
----
. Cambia il ruolo dell'utente. Inserisci:
+
[listing]
----
security login modify -user-or-group-name <username> -application console|http|ontapi|ssh|telnet -authentication-method password -role admin
----
. Torna alla NetApp Console per utilizzare Ransomware Resilience.

