---
sidebar: sidebar 
permalink: rp-use-overview.html 
keywords: ransomware protection, ransomware protection, detect ransomware attacks, recover from ransomware attack 
summary: Utilizzando NetApp Ransomware Resilience, puoi visualizzare lo stato di integrità del carico di lavoro e proteggerlo. 
---
= Utilizza NetApp Ransomware Resilience
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Con NetApp Ransomware Resilience puoi visualizzare lo stato di integrità del carico di lavoro e proteggerlo.

* link:rp-start-discover.html["Scopri i carichi di lavoro in Ransomware Resilience"] .
* link:rp-use-dashboard.html["Visualizza la protezione e lo stato del carico di lavoro dalla Dashboard"] .
+
** Esaminare e agire di conseguenza sulle raccomandazioni per la protezione dal ransomware.


* link:rp-use-protect.html["Proteggere i carichi di lavoro"]:
+
** Assegnare una strategia di protezione dal ransomware ai carichi di lavoro.
** Aumenta la protezione delle applicazioni per prevenire futuri attacchi ransomware.
** Crea, modifica o elimina una strategia di protezione.


* link:rp-use-alert.html["Rispondere al rilevamento di potenziali attacchi ransomware"] .
* link:rp-use-recover.html["Recuperare da un attacco"](dopo che gli incidenti sono stati neutralizzati).
* link:rp-use-settings.html["Configurare le impostazioni di protezione"] .

