= Valutazione del rischio per la sicurezza da parte di Digital Advisor
:allow-uri-read: 




[[security-risk-assessment-from-digital-advisor]]
=== Valutazione del rischio per la sicurezza da parte di Digital Advisor

La protezione ransomware di BlueXP ora raccoglie informazioni sui rischi di sicurezza del cluster elevati e critici da NetApp Digital Advisor. Se viene rilevato un rischio, la protezione ransomware di BlueXP mostra questo suggerimento nel riquadro *Azioni consigliate* della Dashboard: "Correggi una vulnerabilità di sicurezza nota sul cluster <name>." Dal suggerimento della Dashboard, seleziona *Rivedi e correggi* per consultare Digital Advisor e il relativo articolo Common Vulnerability & Exposure (CVE). Se sono presenti più rischi di sicurezza, consulta i dettagli in Digital Advisor.

Fare riferimento a https://docs.netapp.com/us-en/active-iq/index.html["Documentazione Digital Advisor"^] .



[[back-up-to-google-cloud-platform]]
=== Esegui il backup su Google Cloud Platform

Con questa versione, puoi impostare una destinazione di backup su un bucket di Google Cloud Platform.  In precedenza, era possibile aggiungere destinazioni di backup solo a NetApp StorageGRID, Amazon Web Services e Microsoft Azure.

https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-backup-destination.html["Scopri di più sulla configurazione delle impostazioni BlueXP ransomware protection"].



[[support-for-google-cloud-platform]]
=== Supporto per Google Cloud Platform

Il servizio ora supporta Cloud Volumes ONTAP per Google Cloud Platform per la protezione dell'archiviazione.  In precedenza, il servizio supportava solo Cloud Volumes ONTAP per Amazon Web Services e Microsoft Azure insieme a NAS locali.

https://docs.netapp.com/us-en/data-services-ransomware-resilience/concept-ransomware-resilience.html["Scopri di più sulla BlueXP ransomware protection e sulle origini dati supportate, sulle destinazioni di backup e sugli ambienti di lavoro"] .



[[role-based-access-control]]
=== Controllo degli accessi basato sui ruoli

Ora puoi limitare l'accesso ad attività specifiche con il controllo degli accessi basato sui ruoli (RBAC).  La BlueXP ransomware protection utilizza due ruoli di BlueXP: amministratore dell'account BlueXP e amministratore senza account (visualizzatore).

Per i dettagli sulle azioni che ogni ruolo può eseguire, vedere https://docs.netapp.com/us-en/data-services-ransomware-resilience/rp-reference-roles.html["Privilegi di controllo degli accessi basati sui ruoli"] .
