= Abilita la classificazione dei dati e la scansione per informazioni di identificazione personale (PII)
:allow-uri-read: 




[[enable-data-classification-and-scan-for-personally-identifiable-information-pii]]
=== Abilita la classificazione dei dati e la scansione per informazioni di identificazione personale (PII)

Con questa versione, puoi abilitare la BlueXP classification, un componente fondamentale della famiglia BlueXP , per analizzare e classificare i dati nei carichi di lavoro di condivisione file.  La classificazione dei dati aiuta a identificare se i dati contengono informazioni personali o private, il che può aumentare i rischi per la sicurezza.  Questo processo influisce anche sull'importanza del carico di lavoro e ti aiuta a garantire che i carichi di lavoro vengano protetti con il giusto livello di protezione.

La scansione dei dati PII nella BlueXP ransomware protection è generalmente disponibile per i clienti che hanno implementato la BlueXP classification.  La BlueXP classification è disponibile come parte della piattaforma BlueXP senza costi aggiuntivi e può essere distribuita in locale o nel cloud del cliente.

Per avviare la scansione, nella pagina Protezione, seleziona *Identifica esposizione* nella colonna Esposizione privacy della dashboard Protezione. Per ulteriori informazioni, consulta https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-classify.html["scansione di dati sensibili identificabili personalmente con BlueXP classification"].



[[siem-integration-with-microsoft-sentinel]]
=== Integrazione SIEM con Microsoft Sentinel

Ora puoi inviare dati al tuo sistema di sicurezza e gestione degli eventi (SIEM) per l'analisi e il rilevamento delle minacce tramite Microsoft Sentinel.  In precedenza, era possibile selezionare AWS Security Hub o Splunk Cloud come SIEM.

https://docs.netapp.com/us-en/data-services-ransomware-resilience/task-siem.html["Scopri di più sulla configurazione delle impostazioni BlueXP ransomware protection"].



[[free-trial-now-30-days]]
=== Prova gratuita ora per 30 giorni

Le nuove implementazioni di BlueXP ransomware protection ora hanno una prova gratuita di 30 giorni. In precedenza, BlueXP ransomware protection offriva una prova gratuita di 90 giorni. Se stai già usufruendo della prova gratuita di 90 giorni, quell'offerta continua per 90 giorni.
