= Escludi in blocco gli utenti dagli avvisi sul comportamento degli utenti
:allow-uri-read: 




=== Escludi in blocco gli utenti dagli avvisi sul comportamento degli utenti

Ransomware Resilience ora supporta il caricamento di un elenco JSON di utenti da escludere dagli avvisi sulle attività comportamentali degli utenti, oltre alle opzioni esistenti basate su UI e CSV.

Per ulteriori informazioni, vedere link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/suspicious-user-activity.html#exclude-users-from-alerts["Escludi gli utenti dagli avvisi"^].



=== Miglioramenti dell'attività comportamentale dell'utente

Ransomware Resilience ha migliorato la comprensione del comportamento degli utenti aggiungendo avvisi via email e includendo gli eventi relativi al comportamento degli utenti nei dati degli eventi SIEM supportati (AWS Security Hub, Microsoft Sentinel e Splunk Cloud). Questi miglioramenti forniscono informazioni più accurate sul monitoraggio della sicurezza e della conformità.

Per ulteriori informazioni, vedere link:https://docs.netapp.com/us-en/data-services-ransomware-resilience/suspicious-user-activity.html["Collega NetApp Ransomware Resilience a un SIEM"^].
